export const
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    LOGOUT = 'LOGOUT',
    SET_USER = 'SET_USER',
    SET_USERS = 'SET_USERS',
    GET_USERS_REQUEST = 'GET_USERS_REQUEST',
    GET_USERS_FAILURE = 'GET_USERS_FAILURE'