// <auto-generated />
namespace HunterDevBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TagsandPreview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TagsandPreview));
        
        string IMigrationMetadata.Id
        {
            get { return "201808241452488_Tags and Preview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
